# Generated by Django 2.2.2 on 2019-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spice_name', models.CharField(max_length=200)),
                ('spice_flavour_profile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpiceMixes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spice_mix_name', models.CharField(max_length=200)),
                ('spices_id', models.ManyToManyField(to='spices.Spice')),
            ],
        ),
        migrations.AddField(
            model_name='spice',
            name='spice_mix',
            field=models.ManyToManyField(to='spices.SpiceMixes'),
        ),
    ]
